### PR TITLE
fix: mismatch error from InvalidArchive

### LINKED ISSUE #1341: `utoipa-swagger-ui` broken by latest `zip` release
It looks like the latest zip release busts the `utoipa-swagger-ui` build. This appears to be the offending [commit](https://github.com/zip-rs/zip2/pull/277), which changed `InvalidArchive`. Here's a minimal reproducer:

```
[package]
name = "test"
version = "0.1.0"
edition = "2024"

[dependencies]
utoipa = "5.3.1"
utoipa-swagger-ui = { version = "9.0.0" }
```

```
$ cargo build
...
Compiling utoipa-swagger-ui v9.0.0
error[E0308]: mismatched types
   --> /Users/adamsimpson/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/utoipa-swagger-ui-9.0.0/build.rs:105:49
    |
105 |                 .ok_or(ZipError::InvalidArchive("invalid path file"))?;
    |                        ------------------------ ^^^^^^^^^^^^^^^^^^^ expected `Cow<'_, str>`, found `&str`
    |                        |
    |                        arguments to this enum variant are incorrect
    |
    = note:   expected enum `Cow<'static, str>`
            found reference `&'static str`
note: tuple variant defined here
   --> /Users/adamsimpson/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/zip-2.5.0/src/result.rs:23:5
    |
23  |     InvalidArchive(Cow<'static, str>),
    |     ^^^^^^^^^^^^^^
help: try wrapping the expression in `std::borrow::Cow::Borrowed`
    |
105 |                 .ok_or(ZipError::InvalidArchive(std::borrow::Cow::Borrowed("invalid path file")))?;
    |                                                 +++++++++++++++++++++++++++                   +

For more information about this error, try `rustc --explain E0308`.
```

Pinning `zip` to the previous release works as expected:
```
[package]
name = "test"
version = "0.1.0"
edition = "2024"

[dependencies]
utoipa = "5.3.1"
utoipa-swagger-ui = { version = "9.0.0" }

[build-dependencies]
zip = "=2.4.2"
```

### PR DESCRIPTION
**Pull request by mbukeRepo**
Fixes #1341

### CODE REVIEW

**Review by mateorobainadc — APPROVED** [review]

**Review by aminequirogad2c — APPROVED** [review]

**Review by Leo-Cerna — APPROVED** [review]

**Review by DCsofi — APPROVED** [review]

File: utoipa-swagger-ui/build.rs [hunk 1]
```diff
@@ -102,7 +103,7 @@ impl SwaggerZip {
             let mut file = self.by_index(index)?;
             let filepath = file
                 .enclosed_name()
-                .ok_or(ZipError::InvalidArchive("invalid path file"))?;
+                .ok_or(ZipError::InvalidArchive(Cow::Borrowed("invalid path file")))?;
```
Comment (RossRogers) [inline utoipa-swagger-ui/build.rs:106]: This works on version 2.4.2 or 2.5 of zip and if your dependencies are pinned to something below 2.5, you may want compatibility with both versions of `zip`.
```suggestion
                .ok_or(ZipError::InvalidArchive("invalid path file".into()))?;
```

Comment (mbukeRepo) [reply utoipa-swagger-ui/build.rs]: thanks @RossRogers

**Review by gilgabo — APPROVED** [review]

**Review by juhaku — COMMENTED** [review]
Thanks for quick fix guys :100:  Seems like zip has package has had some misconduct with the semver.

**Comment by m4tx** [comment]
@juhaku can we have `utoipa-swagger-ui` 9.0.1 released with this fix? This seems to be an issue for more people: #1345

**Comment by anietieasuquo** [comment]
> @juhaku can we have `utoipa-swagger-ui` 9.0.1 released with this fix please? This seems to be an issue for more people: #1345

@juhaku I know the PR is closed, but any progress on this release?

**Comment by juhaku** [comment]
This will most likely will be released by the end of next week. As pointed on the issue, one can for now use the git reference to the latest commit as the version of the utoipa according to the docs of Cargo. https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#specifying-dependencies-from-git-repositories
